---
# tasks file for myrole
- name: Task is running from within the role
  ansible.builtin.debug:
    msg: "This is a task from my_role."

- name: new task!
  ansible.builtin.debug:
    msg: "New task!"

- name: new task again
  ansible.builtin.debug:
    msg: "New task again!"

- name: Run get request
  delegate_to: localhost
  ansible.builtin.uri:
    url: https://{{ inventory_hostname }}/get
    method: GET
    status_code: 200
  register: get_request

- name: Debug get request
  ansible.builtin.debug:
    var: get_request

- name: Auth HTTP task
  delegate_to: localhost
  ansible.builtin.uri:
    url: https://{{ inventory_hostname }}/basic-auth/username/password
    method: GET
    status_code: 200
    user: username
    password: "{{ hashi_password }}"
  register: auth_request
